//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 04.06.2010 17:57:09
namespace DUETCPMConsole.LoggingLayer
{
    
    /// <summary>
    /// There are no comments for LogsEntities in the schema.
    /// </summary>
    public partial class LogsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new LogsEntities object using the connection string found in the 'LogsEntities' section of the application configuration file.
        /// </summary>
        public LogsEntities() : 
                base("name=LogsEntities", "LogsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LogsEntities object.
        /// </summary>
        public LogsEntities(string connectionString) : 
                base(connectionString, "LogsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LogsEntities object.
        /// </summary>
        public LogsEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "LogsEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Operations in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Operations> Operations
        {
            get
            {
                if ((this._Operations == null))
                {
                    this._Operations = base.CreateQuery<Operations>("[Operations]");
                }
                return this._Operations;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Operations> _Operations;
        /// <summary>
        /// There are no comments for Worklogs in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Worklogs> Worklogs
        {
            get
            {
                if ((this._Worklogs == null))
                {
                    this._Worklogs = base.CreateQuery<Worklogs>("[Worklogs]");
                }
                return this._Worklogs;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Worklogs> _Worklogs;
        /// <summary>
        /// There are no comments for Operations in the schema.
        /// </summary>
        public void AddToOperations(Operations operations)
        {
            base.AddObject("Operations", operations);
        }
        /// <summary>
        /// There are no comments for Worklogs in the schema.
        /// </summary>
        public void AddToWorklogs(Worklogs worklogs)
        {
            base.AddObject("Worklogs", worklogs);
        }
    }
    /// <summary>
    /// There are no comments for LogsModel.Operations in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SessionID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LogsModel", Name="Operations")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Operations : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Operations object.
        /// </summary>
        /// <param name="sessionID">Initial value of SessionID.</param>
        /// <param name="functionType">Initial value of FunctionType.</param>
        /// <param name="transactAmount">Initial value of TransactAmount.</param>
        public static Operations CreateOperations(long sessionID, int functionType, decimal transactAmount)
        {
            Operations operations = new Operations();
            operations.SessionID = sessionID;
            operations.FunctionType = functionType;
            operations.TransactAmount = transactAmount;
            return operations;
        }
        /// <summary>
        /// There are no comments for Property SessionID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long SessionID
        {
            get
            {
                return this._SessionID;
            }
            set
            {
                this.OnSessionIDChanging(value);
                this.ReportPropertyChanging("SessionID");
                this._SessionID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SessionID");
                this.OnSessionIDChanged();
            }
        }
        private long _SessionID;
        partial void OnSessionIDChanging(long value);
        partial void OnSessionIDChanged();
        /// <summary>
        /// There are no comments for Property ClientAccountID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ClientAccountID
        {
            get
            {
                return this._ClientAccountID;
            }
            set
            {
                this.OnClientAccountIDChanging(value);
                this.ReportPropertyChanging("ClientAccountID");
                this._ClientAccountID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ClientAccountID");
                this.OnClientAccountIDChanged();
            }
        }
        private global::System.Nullable<int> _ClientAccountID;
        partial void OnClientAccountIDChanging(global::System.Nullable<int> value);
        partial void OnClientAccountIDChanged();
        /// <summary>
        /// There are no comments for Property ContrAgentAccountID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ContrAgentAccountID
        {
            get
            {
                return this._ContrAgentAccountID;
            }
            set
            {
                this.OnContrAgentAccountIDChanging(value);
                this.ReportPropertyChanging("ContrAgentAccountID");
                this._ContrAgentAccountID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ContrAgentAccountID");
                this.OnContrAgentAccountIDChanged();
            }
        }
        private global::System.Nullable<int> _ContrAgentAccountID;
        partial void OnContrAgentAccountIDChanging(global::System.Nullable<int> value);
        partial void OnContrAgentAccountIDChanged();
        /// <summary>
        /// There are no comments for Property ContrAgentClientAccountID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ContrAgentClientAccountID
        {
            get
            {
                return this._ContrAgentClientAccountID;
            }
            set
            {
                this.OnContrAgentClientAccountIDChanging(value);
                this.ReportPropertyChanging("ContrAgentClientAccountID");
                this._ContrAgentClientAccountID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ContrAgentClientAccountID");
                this.OnContrAgentClientAccountIDChanged();
            }
        }
        private global::System.Nullable<int> _ContrAgentClientAccountID;
        partial void OnContrAgentClientAccountIDChanging(global::System.Nullable<int> value);
        partial void OnContrAgentClientAccountIDChanged();
        /// <summary>
        /// There are no comments for Property ContractBindID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ContractBindID
        {
            get
            {
                return this._ContractBindID;
            }
            set
            {
                this.OnContractBindIDChanging(value);
                this.ReportPropertyChanging("ContractBindID");
                this._ContractBindID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ContractBindID");
                this.OnContractBindIDChanged();
            }
        }
        private global::System.Nullable<int> _ContractBindID;
        partial void OnContractBindIDChanging(global::System.Nullable<int> value);
        partial void OnContractBindIDChanged();
        /// <summary>
        /// There are no comments for Property ExternalDocDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ExternalDocDate
        {
            get
            {
                return this._ExternalDocDate;
            }
            set
            {
                this.OnExternalDocDateChanging(value);
                this.ReportPropertyChanging("ExternalDocDate");
                this._ExternalDocDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ExternalDocDate");
                this.OnExternalDocDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ExternalDocDate;
        partial void OnExternalDocDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnExternalDocDateChanged();
        /// <summary>
        /// There are no comments for Property ExternalDocNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalDocNumber
        {
            get
            {
                return this._ExternalDocNumber;
            }
            set
            {
                this.OnExternalDocNumberChanging(value);
                this.ReportPropertyChanging("ExternalDocNumber");
                this._ExternalDocNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ExternalDocNumber");
                this.OnExternalDocNumberChanged();
            }
        }
        private string _ExternalDocNumber;
        partial void OnExternalDocNumberChanging(string value);
        partial void OnExternalDocNumberChanged();
        /// <summary>
        /// There are no comments for Property feeAmount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> feeAmount
        {
            get
            {
                return this._feeAmount;
            }
            set
            {
                this.OnfeeAmountChanging(value);
                this.ReportPropertyChanging("feeAmount");
                this._feeAmount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("feeAmount");
                this.OnfeeAmountChanged();
            }
        }
        private global::System.Nullable<decimal> _feeAmount;
        partial void OnfeeAmountChanging(global::System.Nullable<decimal> value);
        partial void OnfeeAmountChanged();
        /// <summary>
        /// There are no comments for Property FunctionType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int FunctionType
        {
            get
            {
                return this._FunctionType;
            }
            set
            {
                this.OnFunctionTypeChanging(value);
                this.ReportPropertyChanging("FunctionType");
                this._FunctionType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FunctionType");
                this.OnFunctionTypeChanged();
            }
        }
        private int _FunctionType;
        partial void OnFunctionTypeChanging(int value);
        partial void OnFunctionTypeChanged();
        /// <summary>
        /// There are no comments for Property PaymentDetails in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentDetails
        {
            get
            {
                return this._PaymentDetails;
            }
            set
            {
                this.OnPaymentDetailsChanging(value);
                this.ReportPropertyChanging("PaymentDetails");
                this._PaymentDetails = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PaymentDetails");
                this.OnPaymentDetailsChanged();
            }
        }
        private string _PaymentDetails;
        partial void OnPaymentDetailsChanging(string value);
        partial void OnPaymentDetailsChanged();
        /// <summary>
        /// There are no comments for Property TransactAmount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TransactAmount
        {
            get
            {
                return this._TransactAmount;
            }
            set
            {
                this.OnTransactAmountChanging(value);
                this.ReportPropertyChanging("TransactAmount");
                this._TransactAmount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TransactAmount");
                this.OnTransactAmountChanged();
            }
        }
        private decimal _TransactAmount;
        partial void OnTransactAmountChanging(decimal value);
        partial void OnTransactAmountChanged();
        /// <summary>
        /// There are no comments for Property CurrentDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> CurrentDate
        {
            get
            {
                return this._CurrentDate;
            }
            set
            {
                this.OnCurrentDateChanging(value);
                this.ReportPropertyChanging("CurrentDate");
                this._CurrentDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CurrentDate");
                this.OnCurrentDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _CurrentDate;
        partial void OnCurrentDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCurrentDateChanged();
        /// <summary>
        /// There are no comments for Property Result in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Result
        {
            get
            {
                return this._Result;
            }
            set
            {
                this.OnResultChanging(value);
                this.ReportPropertyChanging("Result");
                this._Result = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Result");
                this.OnResultChanged();
            }
        }
        private global::System.Nullable<int> _Result;
        partial void OnResultChanging(global::System.Nullable<int> value);
        partial void OnResultChanged();
        /// <summary>
        /// There are no comments for Property ResultNote in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultNote
        {
            get
            {
                return this._ResultNote;
            }
            set
            {
                this.OnResultNoteChanging(value);
                this.ReportPropertyChanging("ResultNote");
                this._ResultNote = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ResultNote");
                this.OnResultNoteChanged();
            }
        }
        private string _ResultNote;
        partial void OnResultNoteChanging(string value);
        partial void OnResultNoteChanged();
        /// <summary>
        /// There are no comments for Property ResultLog in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultLog
        {
            get
            {
                return this._ResultLog;
            }
            set
            {
                this.OnResultLogChanging(value);
                this.ReportPropertyChanging("ResultLog");
                this._ResultLog = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ResultLog");
                this.OnResultLogChanged();
            }
        }
        private string _ResultLog;
        partial void OnResultLogChanging(string value);
        partial void OnResultLogChanged();
    }
    /// <summary>
    /// There are no comments for LogsModel.Worklogs in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LogsModel", Name="Worklogs")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Worklogs : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Worklogs object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="time">Initial value of Time.</param>
        /// <param name="message">Initial value of Message.</param>
        public static Worklogs CreateWorklogs(int id, global::System.DateTime time, string message)
        {
            Worklogs worklogs = new Worklogs();
            worklogs.ID = id;
            worklogs.Time = time;
            worklogs.Message = message;
            return worklogs;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this.ReportPropertyChanging("Code");
                this._Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Code");
                this.OnCodeChanged();
            }
        }
        private global::System.Nullable<int> _Code;
        partial void OnCodeChanging(global::System.Nullable<int> value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Time in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this.ReportPropertyChanging("Time");
                this._Time = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Time");
                this.OnTimeChanged();
            }
        }
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();
        /// <summary>
        /// There are no comments for Property Message in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this._Message;
            }
            set
            {
                this.OnMessageChanging(value);
                this.ReportPropertyChanging("Message");
                this._Message = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Message");
                this.OnMessageChanged();
            }
        }
        private string _Message;
        partial void OnMessageChanging(string value);
        partial void OnMessageChanged();
        /// <summary>
        /// There are no comments for Property Tip in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Tip
        {
            get
            {
                return this._Tip;
            }
            set
            {
                this.OnTipChanging(value);
                this.ReportPropertyChanging("Tip");
                this._Tip = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Tip");
                this.OnTipChanged();
            }
        }
        private string _Tip;
        partial void OnTipChanging(string value);
        partial void OnTipChanged();
    }
}
